## Numpy (AI Viet Nam- 16/09/2020)
### Introduction and applications to data processing

### Introduction to Numpy

#### Numpy arrays are multi-dimensional arrays

#### [1] 1D array; 2D array; 3D array
#### [2] Create Numpy array
#### a. From list: arr_np = np.array(python_list)

In [ ]:
# aivietnam
# tao mang array tu list

import numpy as np

# taolist    
a_list = list(range(4))   
print(a_list)

# tao ndarray
arr = np.array(a_list)

print(type(arr))
print(arr)
print(arr[0])
print(arr[1])

[0, 1, 2, 3]
<class 'numpy.ndarray'>
[0 1 2 3]
0
1


#### b. Common attibutes
#### b.1. dtype: data type
#### b.2. shape: return a tuple of #elemens in each dimension
#### b.3. ndim: return #dimensions

In [ ]:
# aivietnam
# tao mang array tu list
import numpy as np
 
# tao list    
a_list = list(range(4))   
print(a_list)

# tao ndarray
arr = np.array(a_list)

print(type(arr))
print(arr.shape)

[0, 1, 2, 3]
<class 'numpy.ndarray'>
(4,)


In [ ]:
# tao mang array tu list

import numpy as np

# tao list
list2d = [(1,2),
            (3,4),
             (5,6)]

# tao ndarray
arr = np.array(list2d)

print(arr.shape)
print(arr)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# tao ndarray tu list

import numpy as np

#tao list
list3D = [[[1,6], [2,2],[3,4]],
          [[4,7], [5,2],[6,9]],
          [[7,7],[8,2],[9,5]]]
print(list3D)
#tao ndarray
data = np.array(list3D)

#print(data)
print(data.shape)


[[[1, 6], [2, 2], [3, 4]], [[4, 7], [5, 2], [6, 9]], [[7, 7], [8, 2], [9, 5]]]
(3, 3, 2)


In [ ]:
# dtype example
# tao ndarray
data1 = np.array([1,2,3])
print(data1)
print(data1.dtype)

data2 = np.array([1.,2.,3.])
print(data2)
print(data2.dtype)

data3 = np.array([1,2,3], dtype = np.int64)
print(data3.dtype)

[1 2 3]
int32
[1. 2. 3.]
float64
int64


#### c. Update an element

In [1]:
# thay doi gia tri phan tu
import numpy as np

# tao list
l = list(range(1,4))

#tao ndarray
data = np.array(l)
print(data)

data[0]=8
print(data)

[1 2 3]
[8 2 3]


#### zeros() function 

In [ ]:
import numpy as np
#shape: 2 dong, 3 cot
arr = np.zeros((2,3))
print (arr)

[[0. 0. 0.]
 [0. 0. 0.]]


#### ones() function

In [3]:
import numpy as np
# numpy.ones(shape)
# shape: 2 dong, 3 cot
arr =  np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


#### full() function

In [4]:
# tao mot numpy array voi ta ca cac phan tu la hang so fill_value
import numpy as np
# numpy.full(shape, fill_value)
# shape: 2 dong,, 3 cot
arr = np.full((2,3),9)
print(arr)

[[9 9 9]
 [9 9 9]]


#### arange() function

In [5]:
import numpy as np
# np.arange(start=1, stop, step = 3)
arr =  np.arange(1,9,3)
print(arr)

[1 4 7]


#### eye() function

In [6]:
# Tao mot numpy array voi duong cheo la so 1
# so 0 duoc dien vap nhung o phan tu con lai
import numpy as np
# numpy.eye(N)
# shape: 5 dong, 5 cot
arr =  np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### random() function

In [7]:
# Tao mot numpy array voi gia tri ngau nhien
import numpy as np
#np.random.random(size)
# shape: 2 dong, 3 cot voi phan tu co gia tri ngau nhien
arr =  np.random.random((2,3))
print(arr)

[[0.32694363 0.90947201 0.7819953 ]
 [0.35043571 0.25531551 0.2408059 ]]


#### d. Some important functions
#### where() function

In [8]:
import numpy as np
#create an array
arr =  np.arange(2,5)
print(arr)

output = arr -1
print(output)

[2 3 4]
[1 2 3]


In [ ]:
import numpy as np

arr =  np.arange(1,5)
mask = arr<3
print(mask)

[ True  True False False]


In [9]:
import numpy as np
#create an array
arr =  np.arange(1,5)
print(arr)

# condition
condition = arr <3
out = np.where(condition, arr, arr*2)

print(condition)
print(out)

[1 2 3 4]
[ True  True False False]
[1 2 6 8]


#### flatten() function

In [ ]:
import numpy as np

arr = np.array([[1,2],[3,4]])
out = arr.flatten()

print(arr)
print(out)

[[1 2]
 [3 4]]
[1 2 3 4]


#### reshape() function

In [12]:
import numpy as np
# create a list
l= [[1,2,3],
   [4,5,6]]
# create ndarray
data = np.array(l)
print('data\n',data)
print('data shape\n', data.shape)
#reshape
data_rs = np.reshape(data, (3,2))
print('data_rs\n',data_rs)
print('data_rs shape\n', data_rs.shape)

data
 [[1 2 3]
 [4 5 6]]
data shape
 (2, 3)
data_rs
 [[1 2]
 [3 4]
 [5 6]]
data_rs shape
 (3, 2)


### Array Indexing
#### 1. Slicing
#### arr[for_axis_0, for_axis_1,...]
#### ':' : get all the elements
#### 'a:b': get the elements from ath to (bth -1)

#### Slicing

In [ ]:
import numpy as np
# khoi tao numpy array arr
arr = np.array([[1,2,3],
                [4,5,6],
                  [7,8,9]])
print(arr.shape)
# Su dung slicing de tao mang sub_arr
sub_arr = arr[1:,1:] #(arr[1:3,1:3])
print(sub_arr)

(3, 3)
[[5 6]
 [8 9]]


#### Mutable

#### Get a row

In [13]:
import numpy as np

# Tao mot mang array

arr = np.array([[1,2,3],
               [5,6,7],
               [9,10,11]])
#Hai cac truy cap du lieu o dong index=1
#cach 1: so chieu giam
row_m1 = arr[1,:]

#cach 2: so chieu duoc giu nguyen
row_m2 = arr[1:2, :]

print(row_m1, row_m1.shape)
print(row_m2,row_m2.shape)

[5 6 7] (3,)
[[5 6 7]] (1, 3)


Get a column

In [15]:
import numpy as np
# Tao mot numpy array co shape (3,3) voi gia tri
arr = np.array([[1,2,3],
               [5,6,7],
               [9,10,11]])
# Hai cach truy cap du lieu o cot index=1 cua mang
#cach 1: so chieu giam
col_m1 = arr[:,1]
#cach 2: so chieu duoc giu nguyen
col_m2 = arr[:,1:2]

print(col_m1, col_m1.shape)
print(col_m2, col_m2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### 2. Using Lists as indices

In [16]:
import numpy as np
# tao arr
arr = np.array([[1,2],
                [3,4],
                [5,6]])
# lay gia tri vi tri (0,0),(1,1) va (2,0)
out1 = arr[[0,1,2],[0,1,0]]
print('out1:\n', out1)

# co the truy cuat toi 1 phan tu nhieu hon 1 lan
out2 = arr[[0,0],[1,1]]
print('out2:\n', out2)

out1:
 [1 4 5]
out2:
 [2 2]


#### 3. Boolean indices

In [ ]:
import numpy as np

arr = np.arange(9)
print(arr)
# Tim phan tu lon hon 4
mask = arr>4
print(mask)

output = arr[mask]
print(output)

[0 1 2 3 4 5 6 7 8]
[False False False False False  True  True  True  True]
[5 6 7 8]


In [ ]:
import numpy as np

arr = np.arange(9)
print(arr)

mask = (arr%2==0)
print(mask)

output = arr[mask]
print(output)

[0 1 2 3 4 5 6 7 8]
[ True False  True False  True False  True False  True]
[0 2 4 6 8]


### Numpy array operations
#### 1. Division

In [ ]:
x = 3
y = 7
print(y/x)
print(y//x)

2.3333333333333335
2


In [ ]:
import numpy as np

arr1 = np.array([2,2,4])
arr2 = np.array([7,8,9])

print(arr2/arr1)
print(arr2//arr1)

[3.5  4.   2.25]
[3 4 2]


#### 2. Square root

In [17]:
import numpy as np

data = np.array([1,2,3,4])

print('data \n', data)

# Can bac hai tung phan tu trogn data
print('sqrt \ n', np.sqrt(data))

data 
 [1 2 3 4]
sqrt \ n [1.         1.41421356 1.73205081 2.        ]


#### 3. Inner product

In [19]:
import numpy as np

v = np.array([1,2])
w = np.array([2,3])

# Tinh inner product giua v va w
print('method 1 \n', v.dot(w))
print('method 2 \n', np.dot(v,w))

method 1 
 8
method 2 
 8


#### 4. Vector-matrix multiplication

In [25]:
import numpy as np

X = np.array([[1,2],
             [3,4]])
v = np.array([1,2])

print('matrix X \n', X)
print('vector v \n', v)

#phep nhan giua ma tran va vector
print('method 1: X.dot(v)', X.dot(v))
print('method 1:, v.dot(X)', v.dot(X))
#print('n\ method 2 \n',np.dot(X,v))
#print('n\ method 2 \n',np.dot(v,X))

matrix X 
 [[1 2]
 [3 4]]
vector v 
 [1 2]
method 1: X.dot(v) [ 5 11]
method 1:, v.dot(X) [ 7 10]


#### 5. Matrix-matrix multiplication

In [28]:
import numpy as np

X = np.array([[1,2],
             [3, 4]])
Y = np.array([[2,2],
             [2,1]])
# Phep nhan giua hai ma tran
print('method 1:', X.dot(Y))
print('method 1:', Y.dot(X))
#print('method 2 \n', np.dot(X,Y))
# print('method 2 \n', np.dot(Y,X))

method 1: [[ 6  4]
 [14 10]]
method 1: [[ 8 12]
 [ 5  8]]


#### 6. Transpose

In [29]:
import numpy as np

X = np.array ([[1,2],
               [3,4]])
print(X)
#traspose
print(X.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


#### 7.  Summation

In [ ]:
arr = np.random.randint(9, size=(3,2))
print(arr.shape)
print(arr)

sum1 = arr.sum()
print(sum1)

sum2 = arr.sum(axis=0)
print(sum2)

sum3 = arr.sum(axis=1)
print(sum3)

(3, 2)
[[2 3]
 [4 7]
 [7 4]]
27
[13 14]
[ 5 11 11]


In [30]:
import numpy as np

X = np.array([[1,2],
             [3,4]])
# Tong cac phan tu cua mang
print(np.sum(X))
# Tinh tong theo tung cot 
print(np.sum(X, axis=0))
# Tinh tong theo tung dong
print(np.sum(X, axis =1))

10
[4 6]
[3 7]


#### 8. Max and min

In [31]:
import numpy as np

data = np.array([1,2,3])

print(data.max())
print(data.min())

3
1


### Broadcasting

#### 1. Vector anf a scalar

In [32]:
import numpy as np
#create data
data = np.array([1,2,3])
factor = 2
#broadcasting
result_multiplication = data*factor
result_minus = data -factor

print(data)
print(result_multiplication)
print(result_minus)

[1 2 3]
[2 4 6]
[-1  0  1]


#### 2. Matrix and vector

In [33]:
import numpy as np

X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
v = np.array([1,0,1])

Y = X + v
print(Y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Data Processing

#### 1. Text data

#### a. IRIS data

In [39]:
# Doc file Iris.csv
import numpy as np
import numpy.core.defchararray as np_f

#lay cac dac trung va luu vao bien X
X = np.genfromtxt('Iris.csv', delimiter = ',',
                  dtype='float', usecols=[0,1,2,3],
                  skip_header=1)
print(X.shape)

#lay species va luu vao bien y
Y = np.genfromtxt('Iris.csv', delimiter = ',',
                  dtype='str', usecols=4,
                  skip_header=1)

# thay chuoi bang so
categories = np.unique(y)
for i in range(categories.size):
  Y = np_f.replace(Y, categories[i], str(i))

  # dua ve kieu float
  Y = Y.astype('float')
  print(Y)

OSError: ignored

#### b. Grayscale images

#### c. Color images

### Image Data
#### 1. Fashion-MNIST dataset

#### Grayscale images
#### Resolution = 28 x 28
#### Training set: 60000 samples
#### testing set: 100000 samples

### Open CV --> chuc nang don gian, hien nay dung tensorflow
#### La thu vien ho tro rat tot
#### goi thu vien CV (install OpenCV conda): pip install OpenCV
